#!/bin/bash
script_directory=`dirname $0`

for test_case in `ls -1 $script_directory/cases`; do
    echo "Test case: $test_case"
    tar xaf $script_directory/cases/$test_case/source.*
    $script_directory/../install.sh -d xkb
    rm -r xkb
done
